apiVersion: v1
data:
  pyweb.py: "# Python 3 server example\nfrom http.server import BaseHTTPRequestHandler,
    HTTPServer\nfrom pathlib import Path\nfrom random import randint\nimport time,os\n\nhostName
    = \"0.0.0.0\"\nserverPort = 8080\n\nclass MyServer(BaseHTTPRequestHandler):\n
    \   def do_GET(self):\n        if os.path.exists('/tmp/ok'):\n            time.sleep(randint(100,1000)/1000)
    \ # Time your app takes to respond\n            self.send_response(200)\n        else:\n
    \           self.send_response(500)\n        self.send_header(\"Content-type\",
    \"text/html\")\n        self.end_headers()\n        self.wfile.write(bytes(\"<html><head><title>https://pythonbasics.org</title></head>\",
    \"utf-8\"))\n        self.wfile.write(bytes(\"<p>Request: %s</p>\" % self.path,
    \"utf-8\"))\n        self.wfile.write(bytes(\"<body>\", \"utf-8\"))\n        self.wfile.write(bytes(\"<p>This
    is an example web server.</p>\", \"utf-8\"))\n        self.wfile.write(bytes(\"</body></html>\",
    \"utf-8\"))\n\nif __name__ == \"__main__\":        \n    Path('/tmp/ok').touch()\n
    \   if os.getenv('DELAY') is not None:\n        time.sleep(int(os.getenv('DELAY')))\n
    \   webServer = HTTPServer((hostName, serverPort), MyServer)\n    print(\"Server
    started http://%s:%s\" % (hostName, serverPort))\n    try:\n        webServer.serve_forever()\n
    \   except KeyboardInterrupt:\n        pass\n\n    webServer.server_close()\n
    \   print(\"Server stopped.\")\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pyweb-script
